kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: wb-lfqa
images:
- name: some-image 
  newName: ghcr.io/some-image
  newTag: 1.2.3
- name: fake-image 
  newName: dockerhub.io/fake-image 
  newTag: 2.3.4

resources:
- pvcs.yaml
